fragment FooterFragment on FooterRecord {
	id
	headline {
		blocks
		links
		value
	}
	text {
		blocks
		links
		value
	}
	buttonText
	link {
		__typename
		... on AboutRecord {
			id
		}
		... on ContactRecord {
			id
		}
	}
}
