fragment ImageWideFragment on FileFieldInterface {
	id
	width
	height
	alt
	basename
	format
	mimeType
	size
	title
	url
	responsiveImage(imgixParams: { w: 4000, auto: format, ar: "16:9", fit: crop }) {
		width
		height
		alt
		aspectRatio
		base64
		bgColor
		sizes
		src
		srcSet
		webpSrcSet
		title
	}
}
