fragment SectionFragment on SectionRecord {
	id
	headline {
		blocks
		links
		value
	}
	text {
		blocks {
			__typename
			... on ExpandableListRecord {
				id
				items {
					id
					title
					text {
						blocks
						links
						value
					}
				}
			}
			... on ImageGalleryRecord {
				id
				images {
					...ImageFragment
				}
			}
		}
		links
		value
	}

	referenceProject {
		...ProjectLightFragment
	}
}
