fragment SectionFragment on SectionRecord {
	id
	sectionId
	headline {
		blocks
		links
		inlineBlocks
		value
	}
	text {
		blocks {
			__typename
			... on ExpandableListRecord {
				id
				items {
					id
					title
					text {
						blocks
						links
						value
					}
				}
			}
			... on ImageGalleryRecord {
				id
				images {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				id
				text
				url
			}
		}
		links
		value
	}
	image {
		...ImageFragment
	}
	referenceProject {
		...ProjectLightFragment
	}
}
