query About($locale: SiteLocale) {
	about(locale: $locale) {
		title
		header {
			...HeaderFragment
		}
		sections {
			...SectionFragment
		}
		footer {
			...FooterFragment
		}
	}
	allStaffs(locale: $locale) {
		...StaffFragment
	}
}
