query Join($locale: SiteLocale) {
	join(locale: $locale) {
		...JoinFragment
	}
}

fragment JoinFragment on JoinRecord {
	title
	header {
		...HeaderFragment
	}
	sections {
		...SectionFragment
	}
	footer {
		...FooterFragment
	}
}
