query Offer($locale: SiteLocale) {
	offer(locale: $locale) {
		...OfferFragment
	}
}

fragment OfferFragment on OfferRecord {
	title
	footer {
		...FooterFragment
	}
	header {
		...HeaderFragment
	}
	sections {
		...SectionFragment
	}
	seoMeta {
		title
		description
	}
}
