query Project($locale: SiteLocale, $slug: String) {
	project(locale: $locale, filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

query AllProjects($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allProjects(first: $first, skip: $skip, locale: $locale) {
		...ProjectFragment
	}
	_allProjectsMeta(locale: $locale) {
		count
	}
}

fragment ProjectFragment on ProjectRecord {
	client {
		... on ClientRecord {
			logo {
				...ImageFragment
			}
			name
		}
	}
	image {
		...ImageFragment
	}
	title
	slug
}

fragment ProjectLightFragment on ProjectRecord {
	client {
		... on ClientRecord {
			logo {
				...ImageFragment
			}
			name
		}
	}
	image {
		...ImageFragment
	}
	title
	slug
}
