query Project($locale: SiteLocale, $slug: String) {
	project(locale: $locale, filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

query AllProjects($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allProjects(first: $first, skip: $skip, locale: $locale) {
		...ProjectLightFragment
	}
	_allProjectsMeta(locale: $locale) {
		count
	}
}

fragment ProjectFragment on ProjectRecord {
	title
	headline {
		blocks
		links
		value
	}
	text {
		blocks
		links
		value
	}
	image {
		...ImageFragment
	}
	client {
		... on ClientRecord {
			logo {
				...ImageFragment
			}
			name
		}
	}
	what {
		blocks {
			__typename
			... on ImageGalleryRecord {
				id
				images {
					...ImageFragment
				}
			}
		}
		links
		value
	}
	why {
		blocks {
			__typename
			... on ImageGalleryRecord {
				id
				images {
					...ImageFragment
				}
			}
		}
		links
		value
	}
	result {
		blocks {
			__typename
			... on ImageGalleryRecord {
				id
				images {
					...ImageFragment
				}
			}
		}
		links
		value
	}

	slug
}

fragment ProjectLightFragment on ProjectRecord {
	title
	image {
		...ImageSquareFragment
	}
	headline {
		blocks
		links
		value
	}
	text {
		blocks
		links
		value
	}
	client {
		name
		logo {
			...ImageFragment
		}
	}
	slug
}
