query Showcase($locale: SiteLocale) {
	showcase(locale: $locale) {
		...ShowcaseFragment
	}
}

fragment ShowcaseFragment on ShowcaseRecord {
	title
	header {
		...HeaderFragment
	}
	sections {
		...SectionFragment
	}
	footer {
		...FooterFragment
	}
}

query AllShowcaseProjects(
	$first: IntType = 10
	$skip: IntType = 0
	$locale: SiteLocale
	$slug: String
) {
	allProjects(first: $first, skip: $skip, locale: $locale, filter: { slug: { neq: $slug } }) {
		...ProjectLightFragment
	}
	_allProjectsMeta(locale: $locale, filter: { slug: { neq: $slug } }) {
		count
	}
}
