query Staff($locale: SiteLocale) {
	staff(locale: $locale) {
		...StaffFragment
	}
}

query AllStaff($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allStaffs(first: $first, skip: $skip, locale: $locale) {
		...StaffFragment
	}
	_allStaffsMeta {
		count
	}
}

fragment StaffFragment on StaffRecord {
	id
	name
	image {
		...ImageSquareFragment
	}
	text {
		blocks
		links
		value
	}
	email
}
